<?php

/**
 * @file
 * Contains vtcf.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vtcf_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vtcf module.
    case 'help.page.vtcf':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides ability for views to be filtered using checkboxed list of taxonomies.') . '</p>';
      return $output;

    default:
  }
}
